version: '3.7'
services:

  portal:
    image: php:7-fpm-alpine
    volumes:
      - ./:/var/www/chope_test
    networks:
      - app-network

  api:
    image: php:7-fpm-alpine
    volumes:
      - ./:/var/www/chope_test
    networks:
      - app-network

  # mysql:
  #   image: mysql:5.7
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=verysecret
  #     - MYSQL_DATABASE=yii2advanced
  #     - MYSQL_USER=yii2advanced
  #     - MYSQL_PASSWORD=secret

  webserver:
    image: nginx
    ports:
      - 8008:80
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
